### ISSUE TITLE
pls amend Real auto bed level

### ISSUE THREAD

**Issue by leungtech** [KevinOConnor/klipper#267] opened 2018-03-30 19:56 UTC
klipper just perform a probe test and generate two numbers of x and y. You need to put these two results into the config file. It is not real auto bed level. Can you pls amended these procedure so that the xy parameter generated by the bed_tilt_calibrate can be automatically put into the config file when every time probe procedure done??

**Comment by KevinOConnor** [comment] 2018-03-31 12:33
This is a duplicate of issue #248

**Closed by KevinOConnor** 2018-03-31 12:33 UTC
