### ISSUE TITLE
Negative stepper_z position_endstop values scale the print!

### ISSUE THREAD

**Issue by rlesac** [KevinOConnor/klipper#926] opened 2018-11-24 15:23 UTC
While setting up Klipper, I put in negative values for the stepper_z position_endstop to avoid the nozzle crashing. 
I did a bed mesh calibration, and it would print just fine, so I didn't give it much though
Then I noticed my prints were scaled in the Z axis by ~5-6%.

Changed my position_endstop to 0 and adjusted the bed mesh points acordingly and it is now fine.

My step_distance was correct and didn't need adjusting.

Seems like there could be a calculation problem with negative values.

**Comment by lenne0815** [comment] 2018-11-24 16:31
Happend to me aswell

**Comment by jakep82** [comment] 2018-11-24 18:14
https://github.com/KevinOConnor/klipper/blob/master/config/example-extras.cfg#L16

**Comment by lenne0815** [comment] 2018-11-24 18:20
> https://github.com/KevinOConnor/klipper/blob/master/config/example-extras.cfg#L16

I dont understand ? I use two individual z endstops with linked steppers, i cant use the probe as a general endstop.

**Comment by jakep82** [comment] 2018-11-24 18:45
If you actually home Z with the nozzle below the bed, then sure.  But that's not a common configuration.  I've never seen a printer that homed that way.

**Comment by lenne0815** [comment] 2018-11-24 18:50
Thats why you didnt run into that problem ;) I personally use it so i can freely set offsets when i install new extruders and dont need to offset gcodes, i can just move the endstop position around until the new extruder sits at "0" this works in both directions for longer / shorter extruders. Its possible because i use optical endstops that never touch the bed.

**Comment by rlesac** [comment] 2018-11-24 19:00
> If you actually home Z with the nozzle below the bed, then sure. But that's not a common configuration. I've never seen a printer that homed that way.

Well, then you haven't seen Creality printers :)
I've also put in negative numbers after that being suggested online.

But all that is besides the point. 
No way scaling is the desired effect of the code in any case I can think of.

**Comment by Arksine** [comment] 2018-11-25 12:31
If you are using an endstop position that isn't relative to the bed itself then you need to disable fade adjustment in the bed_mesh module, `fade_end: 0`, otherwise it will squeeze/expand the Z-Axis depending on your endstop position.  

FWIW, while this may be a "common" configuration, I don't think its a recommended one.  Your endstop position should put the nozzle relatively close to the bed.

**Comment by rlesac** [comment] 2018-11-25 12:52
So, it only scales the print with bed mesh enabled, along with fade_end?
If so, it would make sense to write it in the docs or config comments.

**Comment by Arksine** [comment] 2018-11-25 13:09
Yes, it will only do it when z adjustment fading is enabled.  FWIW, while its technically behaving as expected, I can probably come up with a way to compensate for this behavior.

**Comment by CageFox** [comment] 2018-11-25 22:48
Hello!

I have
[stepper_z]
position_min: -1

and 

[probe]
z_offset: 1.38

and
[bed_mesh]
fade_start: 0.4
fade_end: 1.4

Am i also victim of this behaviour? Some strange events hint to me that yes.

**Comment by Arksine** [comment] 2018-11-26 00:45
@CageFox  Its possible, but nothing in your snippet of printer.cfg would indicate that.  I think its more likely that trying to fade out adjustment over 1mm of height is producing visible artifacts.  

After looking at this in more detail, its really difficult to do anything about this in code, doing so could negatively affect other configurations.  I think the best solution is to disable fade by default and document this potential side effect for users that wish to enable it.

**Comment by CageFox** [comment] 2018-11-26 00:51
> @CageFox I think its more likely that trying to fade out adjustment over 1mm of height is producing visible artifacts.

What settings of fade will bring better results? Uppper fade start and much upper fade end?

**Comment by Arksine** [comment] 2018-11-26 01:59
I would try the default values first, fade_start: 1, fade_end: 10.  This phases out the adjustment over 45 layers at .2 resolution, which should be far less visible.

If you notice that fade is significantly affecting the size of your parts along the z-axis as mentioned in this issue, I recommend disabling it by setting fade_end to 0.

**Comment by lenne0815** [comment] 2018-11-26 08:35
What i dont really get is why endstops are a factor for the fade in general, shouldnt it always relate to 0 in the machine coordinate system ?

**Comment by Arksine** [comment] 2018-11-26 16:07
@lenne0815 Lets assume that your bed has a geometric variance of +/- 1mm along the z-axis.  On a properly configured printer, the probe will measure values along the bed in the range of 0 +/- 1mm.  When fade is enabled, it will shrink or grow the print in areas that are below or above zero so by the time you reach fade_end there is no more z-adjustment.

When you add an endstop with a position set to a negative value it is skewing the results from probing.  Let's say you have it set to -2.   Instead of getting results of 0 +/- 1mm, its getting results of -2 +/- 1mm.    With the entire mesh skewed in the negative direction, it will "grow" the print by that amount during the fade operation.

**Comment by KevinOConnor** [comment] 2018-11-26 16:35
> When you add an endstop with a position set to a negative value it is skewing the results from probing. Let's say you have it set to -2. Instead of getting results of 0 +/- 1mm, its getting results of -2 +/- 1mm. With the entire mesh skewed in the negative direction, it will "grow" the print by that amount during the fade operation.

Just so I understand, the issue is not that the position_endstop is negative, but that the position_endstop is wrong?  That is, if the printer did have a Z endstop below the bed and the user did set a negative Z endstop in such a way that the bed is at Z=0 then everything does work okay?  If so, that makes sense to me - the intent is for Z coordinates to be the distance between nozzle and bed - I don't think it is necessary to support other interpretations of Z.

Out of curiosity, though, could the mesh routines calculate an average Z of the bed and then apply fade_start/fade_end relative to that?  Not to fix an incorrectly configured printer, but to better account for minor differences in bed height.  For example, if the user uses a probe:virtual_z_endstop and z homes to a corner of their bed, they could maybe see fade artefacts if that corner is at an extreme low?

-Kevin

**Comment by lenne0815** [comment] 2018-11-26 16:46
> When you add an endstop with a position set to a negative value it is skewing the results from probing. Let's say you have it set to -2. Instead of getting results of 0 +/- 1mm, its getting results of -2 +/- 1mm. With the entire mesh skewed in the negative direction, it will "grow" the print by that amount during the fade operation.

And therein lays the problem, it should still assume that the bed is at 0 ( where it always is ) no matter where the endstop sits, cant you just offset whatever the user has configured to 0 ? ( f.e. user set -2 for endstop - add + 2 to every probe point ? )

**Comment by Arksine** [comment] 2018-11-26 17:56
@KevinOConnor Yes, the way it is set up works when homing off the bed with a negative endstop position.  Essentially it behaves just as it would if there were no bed mesh, when the user enters G0 Z0 it would take the nozzle up to the bed plus a z adjustment based on the current x,y coordinates.

I think it should be possible to average the z coodinates in the mesh and fade to that position rather than zero.  I'll take a deeper look at it and make sure there are no potential issues I am missing.   I do think the situation you describe is another good reason to disable fade by default, as it would certainly cause parts on the rest of the bed to be compressed when fade is enabled.   Generally when homing with a probe I like do so in the middle of the bed with a homing_override as that is where I want my reference to be.  This is something I will add to the documentation.

@lenne0815 It is impossible for me to tell if you are homing off the bed or not, so I can't add the endstop position to the mesh.  When you set the endstop position to -2 Klipper (and bed_mesh) does indeed assume the bed as at Z=0, ie 2mm higher than where your endstop triggered.

**Comment by KevinOConnor** [comment] 2018-12-09 17:39
Thanks.  I'm going to close this as it looks like it was addressed with PR #944.

-Kevin

**Closed by KevinOConnor** 2018-12-09 17:39 UTC
