### ISSUE TITLE
Filament end detected

### ISSUE THREAD

**Issue by TomaszKn** [KevinOConnor/klipper#311] opened 2018-04-29 14:44 UTC
Does Klipper support filament end detected.

Regards
Tom

**Comment by KenshiHH** [comment] 2018-04-29 18:37
https://github.com/KevinOConnor/klipper/tree/master/docs

**Comment by TomaszKn** [comment] 2018-04-29 19:02
Could you write me more precision answer?

**Comment by KevinOConnor** [comment] 2018-04-30 13:53
This looks like a duplicate of issue #249.  Alas, filament sensors are not currently supported.

-Kevin

**Comment by KevinOConnor** [comment] 2018-05-05 15:50
I'm closing this in favor of the existing issue #249.

**Closed by KevinOConnor** 2018-05-05 15:50 UTC
