### ISSUE TITLE
M84 followed by G28 results in error in certain positions

### ISSUE THREAD

**Issue by Pizzahd88** [KevinOConnor/klipper#4624] opened 2021-08-27 09:08 UTC
# Problem
When using M84 (stepper motors turn off), followed by G28 (homing) an error is thrown: "Must home axis first: 345.000 175.000 10.000 [0.000]"
It happens for both absolute and relative positioning, the triggering point seems to be the placement of the toolhead when shutting off motors (M84)

## Steps to replicate:
Run the following G-codes to replicate the issue:
### Absolute position
1. G28
2. G90
3. G1 X335 Y175 Z20 F8000
4. G91 (_OPTIONAL_)
4. M84
5. G28 <---- this will throw the error

### Relative position
1. G28
4. G91
3. G1 X105 Y-182 Z10 F8000 _(This must make the toolhead stop at X335 Y175 Z20 from homing position)_
4. M84
5. G28 <---- this will throw the error

I have tried to invoke M400 and BED_MESH_CLEAR after the G1 move command but none of them got the error to disappear.

Only certain positions results in this error, IF I go with G1 X335 Y330 Z20 F1000 at "Absolute position" step 3 it works without an error.

The printer has homing-bump set to 5, and I see it homes X axis just fine, touches it but instead of backing off, it stops and throws the error as if it cannot back up for the bump.

## Machine info:
Voron 2.4 350mm build volume
My bed size is setup to be 350 at X axis and 357 at Y axis. Z height is 340 in klipper.

Mainsail, Moonraker and Klipper runs the newest versions released
![image](https://user-images.githubusercontent.com/29568847/131108626-72e13dc3-3ef0-4a2d-827a-2f36007dd94a.png)

## Log
[klippy (2).log](https://github.com/KevinOConnor/klipper/files/7065654/klippy.2.log)

## Video clip of the steps above until error
https://youtu.be/iSbbGiY7trk

**Comment by Scotchy49** [comment] 2021-08-28 05:54
Here are the logs you requested.

I restarted klipper, then simply ran the following, which triggered the error.
```
G28
M84
G28
```

[klippy.log](https://github.com/KevinOConnor/klipper/files/7070217/klippy.log)

**Comment by Scotchy49** [comment] 2021-08-28 06:07
After running bisect, the offending commit seems to be efbb704522ec246cc91039f5321f6ccfac88e627

```
scotchy@sidewinder:~/klipper$ git bisect bad
efbb704522ec246cc91039f5321f6ccfac88e627 is the first bad commit
commit efbb704522ec246cc91039f5321f6ccfac88e627
Author: Michael Kurz <michi.kurz@gmail.com>
Date:   Sun Aug 22 13:58:27 2021 +0200

    lpc176x: Fix wrong inital value at PWM setup
    
    This fixes a PWM going to full scale output when a initial value != 0 was
    given. The output was on 100% until another update occurred.
    
    This change enables the PWM counter before setting the channel values.
    
    Fixes KevinOConnor/klipper#4559
    
    Signed-off-by: Michael Kurz <michi.kurz@gmail.com>

 src/lpc176x/hard_pwm.c | 15 +++++++--------
 1 file changed, 7 insertions(+), 8 deletions(-)
scotchy@sidewinder:~/klipper$ 

```

**Comment by Scotchy49** [comment] 2021-08-28 06:33
After some testing, I went back to 69d9497df325b0ea7ef71824f7106ae09fcbcdbb which did not exhibit the issue.
I bisected starting from that commit, and apparently the commit which started the issue is 3814a13251aeca044f6dbbccda706263040e1bec

```
scotchy@sidewinder:~/klipper$ git bisect good
3814a13251aeca044f6dbbccda706263040e1bec is the first bad commit
commit 3814a13251aeca044f6dbbccda706263040e1bec
Author: Kevin O'Connor <kevin@koconnor.net>
Date:   Mon Apr 5 10:59:47 2021 -0400

    homing: Calculate homing position based on trigger time
    
    Calculate the "homing position" using the endstop trigger time instead
    of the position of the steppers.
    
    This is in preparation for multi-mcu homing.
    
    Signed-off-by: Kevin O'Connor <kevin@koconnor.net>

 docs/Config_Changes.md  |  6 ++++
 klippy/extras/homing.py | 73 ++++++++++++++++++++++++++++++++++++-------------
 klippy/stepper.py       |  3 +-
 3 files changed, 62 insertions(+), 20 deletions(-)

```

**Comment by Scotchy49** [comment] 2021-08-28 07:33
After some additional digging, I found that haltpos in https://github.com/KevinOConnor/klipper/blob/8d4d16d51a3e3581b04b49b4fd216a40d4ae7c3d/klippy/extras/homing.py#L129 has some negative values during homing (just before backing off).

The original code, which used movepos, does not receive a negative value during the same move.

**Comment by KevinOConnor** [comment] 2021-08-28 17:09
This looks like a numerical stability issue with the second home retraction movement.  If you pull the latest code from the work-homing-20210827 branch, does the problem go away?  (Specifically commit 22dab9b7.)

`cd ~/klipper ; git fetch ; git checkout origin/work-homing-20210827 ; sudo service klipper restart`

-Kevin

**Comment by Scotchy49** [comment] 2021-08-28 18:44
That seems to have fixed it, thanks a lot!
[klippy.log](https://github.com/KevinOConnor/klipper/files/7071264/klippy.log)

Attached is the log file in case you'd like to see it.

**Comment by KevinOConnor** [comment] 2021-08-28 19:51
Thanks.  I committed that change to the master branch (commit 2e131497).

-Kevin

**Comment by Pizzahd88** [comment] 2021-09-03 06:21
This seems to work as expected with latest version. Big thanks for the speedy fix 👍

**Closed** 2021-09-03 06:20 UTC
Labels: resolved
