### ISSUE TITLE
BL-Touch tip, moves several times while probing, up and down in the Z-movement.

### ISSUE THREAD

**Issue by Metti93** [KevinOConnor/klipper#2456] opened 2020-02-01 12:05 UTC
[klippy.log](https://github.com/KevinOConnor/klipper/files/4142503/klippy.log)

Here a little Video of the issue:  https://imgur.com/a/pT7qvFu

Here my Bed-Visualizer:  https://imgur.com/a/eeGB5EF

While my Ender 3 is measuring the bed using the "G29" command, the tip of the BL-Touch panicked up and down during the Z movement. Which leads to my bed being measured sluggishly.
How so?

**Comment by Metti93** [comment] 2020-02-01 13:43
I have now adjusted the "pin_move_time", under [bltouch], to 1.0. 
As well as "horizontal_move_z", in [bed_mesh], adjusted to 10.

Now he seems to have fewer problems.

**Comment by Metti93** [comment] 2020-02-01 23:55
Nope. A measurement of 20 fails on every case and measures a wrong value

**Comment by KevinOConnor** [comment] 2020-02-14 16:53
FWIW, I personally don't have any insight into the cause of your issues.  Perhaps someone else will chime in.

-Kevin

**Comment by BlackStump** [comment] 2020-02-14 22:06
Creality board + bltouch = problems 

https://github.com/KevinOConnor/klipper/issues/2321

**Comment by DrShats** [comment] 2020-03-06 16:28
Any news on the case? Experiencing same problem on mega2560+rpi3b and on mega2560 + rpi3b+

**Comment by KevinOConnor** [comment] 2020-03-21 15:34
I'm going to close this as it looks like the conversation has concluded.  FYI, there are several BL-Touch fixes in the most recent code.  Also be sure to follow the directions in docs/BL-Touch.md.

-Kevin

**Closed by KevinOConnor** 2020-03-21 15:34 UTC
