### ISSUE TITLE
Error connecting I2S ssd1306 display and turning on the heating BED?

### ISSUE THREAD

**Issue by ShohninDmitriy** [KevinOConnor/klipper#1962] opened 2019-09-12 14:44 UTC
when the heater bed immediately hangs the firmware,connected the screen ssd1306 via i2s.mboard  SKR1.1
[klippy.log](https://github.com/KevinOConnor/klipper/files/3606034/klippy.log)

**Comment by KevinOConnor** [comment] 2019-09-14 20:17
Unfortunately, it looks like something (the bed heater) is causing noise on the i2c lines to the display.  The current micro-controller code does not tolerate noise on the i2c lines.  It may be possible to better shield the i2c lines, it may be possible for someone to implement more robust i2c code on the micro-controller, or it may be possible for you to use a display that does not rely on i2c.

-Kevin

**Comment by ShohninDmitriy** [comment] 2019-09-15 05:06
Let's say that the power supply is noisy but when you switch to the power controller on the usb influence of interference from the power supply immediately excluded and the title of the controller still occurs as soon as the signal is given to heat the hot table, then the error somewhere in the code before it worked, 6 months ago

**Comment by KevinOConnor** [comment] 2019-09-21 23:28
Alas, I don't have any additional advice.

-Kevin

**Comment by KevinOConnor** [comment] 2019-10-08 15:16
I'm going to close this issue as it appears the conversation has concluded.  It is known that the i2c micro-controller code can be finicky on line noise - if the issue isn't line noise then the root cause is not known.

-Kevin

**Closed by KevinOConnor** 2019-10-08 15:16 UTC
