### ISSUE TITLE
Request adding xy skew correction

### ISSUE THREAD

**Issue by leungtech** [KevinOConnor/klipper#266] opened 2018-03-30 19:49 UTC
In marlin, there is a important function called "xy skew correction", this can help to correct xy skew which cause by poor installation of 3d printer, this is very hard to print a perfect square without this function, can you please adding this function??

**Comment by KenshiHH** [comment] 2018-03-30 20:39
once is already enough

https://github.com/KevinOConnor/klipper/issues/258

**Comment by KenshiHH** [comment] 2018-03-30 20:40
seriously, fix your hardware its not that hard

**Comment by leungtech** [comment] 2018-03-31 05:44
0.2mm is hard to fix in hardware, software fixing skew will be easy and more precise

**Comment by KevinOConnor** [comment] 2018-03-31 12:32
This is a duplicate of issue #258.

**Closed by KevinOConnor** 2018-03-31 12:32 UTC
