### ISSUE TITLE
 Lost communication with MCU 'mcu'

### ISSUE THREAD

**Issue by JustAnother1** [KevinOConnor/klipper#1424] opened 2019-03-20 15:56 UTC
[klippy.log.zip](https://github.com/KevinOConnor/klipper/files/2989015/klippy.log.zip)

The print went on for 13 Hours without an issue and then it suddenly stopped.

I did several successful prints on the machine. The USB cable is of good quality and short. Octoprint also does not complain on the power supply. I therefore assume that I did everything I could.

I can not decode the log file. Can anybody tell me what the issue was?

**Comment by hevilp** [comment] 2019-03-20 16:28
I had it too, you are running a raspi? Maybe change sd card, I did it just this hours because of the same problem

**Comment by JustAnother1** [comment] 2019-03-20 16:51
@hevilp Yes this runs on a raspberryPi. I don't want to change the SD Card just on a feeling. Did you check the log file. Was there some indication that the SD card could be the issue?

**Comment by hevilp** [comment] 2019-03-20 17:10
I understand you, I changed my sdcard and it still happens! I changed usb cable, raspi, sd card, power for rpi, and still got the problem, I need help here too

**Comment by hevilp** [comment] 2019-03-20 17:24
[klippy.zip](https://github.com/KevinOConnor/klipper/files/2989362/klippy.zip)

**Comment by hevilp** [comment] 2019-03-20 18:09
I just swapped the usb port from mcu:mcu, so far it it running flawless

**Comment by KevinOConnor** [comment] 2019-03-21 16:45
There's some info on this in the FAQ: https://github.com/KevinOConnor/klipper/blob/master/docs/FAQ.md#i-keep-getting-random-lost-communication-with-mcu-errors

These errors occur at the USB hardware and/or operating system level.  Beyond the info in the FAQ, we don't have any additional information on the root cause.

-Kevin

**Comment by JustAnother1** [comment] 2019-03-22 02:33
I have now used zip ties to fix the USB cable to the raspberryPi. So next time this occurs I can rule out all of the things mentioned in the FAQ.

**Comment by KevinOConnor** [comment] 2019-04-07 13:55
Okay, I'm going to close this issue as it looks like the discussion has ended.

-Kevin

**Closed by KevinOConnor** 2019-04-07 13:55 UTC
