### ISSUE TITLE
Support for both min and max endstop pins per axis

### ISSUE THREAD

**Issue by jrsmiley** [KevinOConnor/klipper#284] opened 2018-04-07 19:28 UTC
Why is there support for only one endstop pin per axis?  Don't most printers have them on both ends?  How much trouble would it be to add support for both min and max endstops per axis (with the option to disable one end on the z axis for bed leveling).

**Comment by KevinOConnor** [comment] 2018-04-08 15:09
This looks like a duplicate of issue #216 .

**Closed** 2018-04-18 22:40 UTC
