### ISSUE TITLE
Can cause a fire!

### ISSUE THREAD

**Issue by ffnull** [KevinOConnor/klipper#155] opened 2018-01-31 18:55 UTC
Printer:Prusa i3
Board: Anet a8
While starting printing. Watchdog didnt work.
My Hotend burnt. Over 400 celsius. There were fire
![default](https://user-images.githubusercontent.com/24982418/35641381-c16da90a-06c8-11e8-804a-980b3c5d5151.png)

**Comment by KevinOConnor** [comment] 2018-01-31 19:38
On Wed, Jan 31, 2018 at 06:55:19PM +0000, ffnull wrote:
> Printer:Prusa i3
> Board: Anet a8
> While starting printing. Watchdog didnt work.
> My Hotend burnt. Over 400 celsius. There were fire

If you want us to take a look at it, you need to attach the klipper
log file from the incident.  See:
https://github.com/KevinOConnor/klipper/blob/master/docs/Contact.md

-Kevin

**Comment by ffnull** [comment] 2018-01-31 19:55
The problem that when its fire. Im cut off power. Log is gone. Sorry

**Comment by NickRimmer** [comment] 2018-01-31 20:12
I think we need some protections for temperature in Host and MCU both.

**Comment by jakep82** [comment] 2018-01-31 20:15
This looks like it was caused by a thermistor, wiring, or board issue.  The temperature was bouncing all over the place before instantly jumping from 150C to 450C.  From there the temperature quickly drops which is probably when the MCU shut down because it was way past the max temperature.  This should probably be addressed with a safety shutoff if the hotend doesn't have a reasonable temperature rise during heat up.

**Comment by Papsnoek** [comment] 2018-02-01 08:42
This does not look like Klipper's fault. Temperature cannot Rise from 150
to 400 instantly... So this would mean the Temperature is faulty and not
reporting the correct temperatures to Klipper.

I think you also might be over reacting about the fire part. According to
the Graph, the Temperature was kept at a stable 240 degrees for over 10
minutes AFTER the fire moment...

Only thing that should come out of this is as jakep82 says, The Shutdown
works fine as this did happen, but maybe some added protection that if
heater is on full power and temperature doesn't rise by a few degrees each
second, then shutdown as this would mean temperature sensor is not
reporting back the correct Temps.

**Comment by ffnull** [comment] 2018-02-01 10:25
Shutdown doest work. Im shut down board manualy. Then were 240 for 10 minutes becouse im dont reflash page. Im starting heating again after replace hot barier and nozle. Quick dropdown were after shutting off 12 power and manual cooling

**Comment by KevinOConnor** [comment] 2018-02-01 14:11
On Wed, Jan 31, 2018 at 12:15:05PM -0800, jakep82 wrote:
> This looks like it was caused by a thermistor, wiring, or board issue.  The temperature was bouncing all over the place before instantly jumping from 150C to 450C.  From there the temperature quickly drops which is probably when the MCU shut down because it was way past the max temperature.  This should probably be addressed with a safety shutoff if the hotend doesn't have a reasonable temperature rise during heat up. 

It's hard to tell without a log, but I agree with your analysis.

-Kevin

**Comment by KevinOConnor** [comment] 2018-02-01 14:12
On Thu, Feb 01, 2018 at 10:25:45AM +0000, ffnull wrote:
> Then were 240 for 10 minutes becouse im dont reflash page.

The klipper log file is stored on the host machine.  If you didn't
power off the host machine, then the log should still be present in
/tmp/

-Kevin

**Comment by ffnull** [comment] 2018-02-01 19:45
Please,read again. No log bicouse im shutting off board. Graphic there becouse im doesnt refrash page. No problems with thermocuple end board. Swithch back to marlin and work good

**Comment by TunaLatte** [comment] 2018-02-02 11:17
I had this type of curve before when the X axis (extruder) was in homing position, it turned out the internal cable was damaged on frequent position (especially homing position) but didn't while printing. I would avoid pretinned wires, solid core copper (like ethernet cables), and recommend twisting the entire cable, would also help against stepper back-emf. The cable bend radius should be minimal when the head moves (especially homing) twisting will also help against sharp bends.

**Comment by psy0rz** [comment] 2018-02-08 20:06
just close this post. one should always make sure the printer isn't near burnable materials. (or just never leave your printer alone)

**Comment by TunaLatte** [comment] 2018-02-08 20:42
@psy0rz agreed, but having thermal runway detection could still help bring down the cost of replacing the entire extruder assembly maybe? especially on hobby printers, e3d heatblock sensor cartidge ceramic bead holder is known to crack after extended periods for example (due to metal contraction) and using a zip tie can pull the sensor slowly overtime, always keep a slack for the wire etc, its still helpful to detect, especially for people that use cork or similar material under heatbed.

**Comment by wizhippo** [comment] 2018-02-08 20:50
Thermal runway detection would be great but if we set the max temps for both the heatbed and the hotend should they not ever be exceeded?  So if I set my max_temp to 210 under extruder and I hit 400 should it not have shutdown?

**Comment by jakep82** [comment] 2018-02-08 21:24
It will only shut down if it knows it's above 210.  In this case the MCU didn't know it was above the max temp until it hit 400, or whatever temperature it actually reached.  This is where minimum thermal rise requirements could help prevent damage.

**Comment by ffnull** [comment] 2018-02-08 21:29
After 400 
![photo_2018-01-17_20-31-02](https://user-images.githubusercontent.com/24982418/35999288-f780899e-0d27-11e8-890d-19ae91bfbd5d.jpg)

**Comment by KevinOConnor** [comment] 2018-02-09 20:00
On Thu, Feb 08, 2018 at 09:24:18PM +0000, jakep82 wrote:
> It will only shut down if it knows it's above 210.  In this case the MCU didn't know it was above the max temp until it hit 400, or whatever temperature it actually reached.  This is where minimum thermal rise requirements could help prevent damage.

Agreed.

FYI, I've been working on "first order plus dead time" calibration
code.  My plan is to implement thermistor checks around this fopdt
model.

-Kevin

**Comment by unverbraucht** [comment] 2018-03-01 09:37
To be totally honest thermal runway protection is what's been keeping me from using this for my Anet. These acryllic printers with mediocre connectors and wiring are fire hazards anyway, and this would give me some peace of mind 👍

**Comment by KevinOConnor** [comment] 2018-03-11 05:51
FYI, commit 5208fc38 adds basic heater and thermistor verification.

**Closed** 2018-03-18 16:59 UTC
