### ISSUE TITLE
Firmware retraction - MCU shutdown: Rescheduled timer in the past

### ISSUE THREAD

**Issue by 1walkerit** [KevinOConnor/klipper#1852] opened 2019-07-30 15:18 UTC
Hi,
I am just testing FW retraction using new slicer. At this time I do not really know where is the proble- if slicer or klipper side.
I've tried to print using FW retraction but got the error -  MCU shutdown: Rescheduled timer in the past - after first layer.
When I tried the same model, same settings but normal retraction  - all is OK. So can you help to find problem - or bug?
Thank you

[gcode-files.zip](https://github.com/KevinOConnor/klipper/files/3447455/gcode-files.zip)
[klippy.log](https://github.com/KevinOConnor/klipper/files/3447492/klippy.log)

**Comment by KevinOConnor** [comment] 2019-08-05 16:39
The error message should have shown up in the OctoPrint terminal:
```
MCU 'mcu' shutdown: Rescheduled timer in the past
This generally occurs when the micro-controller has been
requested to step at a rate higher than it is capable of
obtaining.
Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Printer is shutdown
```

You've requested more steps per second than the micro-controller can support.  The issue is likely related to pressure advance - a similar report is at #865.

-Kevin

**Comment by 1walkerit** [comment] 2019-08-12 12:19
In this case I do not understand why with slicer's retraction it is woriknig and with FW retraction not. The values are the same (retraction speed, lenght and PA). Does it mean if I want to use FW retraction I have to disable PA?

**Comment by KevinOConnor** [comment] 2019-08-17 18:59
Make sure you're using the correct units - Klipper is mm/s while other software sometimes use the (very confusing) mm/minute.  Other than that, I also don't know why they would be different.

-Kevin

**Comment by KevinOConnor** [comment] 2019-09-06 12:47
I'm going to close this issue as it appears the conversation has concluded.

-Kevin

**Closed by KevinOConnor** 2019-09-06 12:47 UTC
